### ISSUE TITLE
NoMethodError `parse_price`

### ISSUE THREAD

**Issue by vlebedeff** [pronix/spree-multi-currency#48]
Hi

When I try to update the product price from the dashboard I get the error

```
[ Currency ] :#<NoMethodError: undefined method `parse_price' for #<Class:0x007ffab8797da8>> 
 /home/vlebedev/.rvm/gems/ruby-2.1.2/gems/activerecord-4.1.7/lib/active_record/dynamic_matchers.rb:26:in `method_missing'\n /home/vlebedev/.rvm/gems/ruby-2.1.2/bundler/gems/spree-multi-currency-7dc093fc5bbc/app/models/spree/currency.rb:132:in `conversion_from_current'
```

**Comment by aadonskoy** [comment]
Hello!
I think the issue connected with this commit https://github.com/spree/spree/commit/b817dab4a95c1beda3f18e42f0efcd2b7e64312a
So parse_price need to be replaced by Spree::LocalizedNumber.parse
I'll try fix it near time.
