### ISSUE TITLE
Locale field is factor for determine current currency

### ISSUE THREAD

**Issue by mbajur** [pronix/spree-multi-currency#49]
Hello.
When i'm trying to use spree-multi-currency, the following error is thrown everywhere:

    Require load and set default currency<br/>Locale field is factor for determine current currency

I'm quite sure that it's something basic but i'm totally not able to understand what does it mean nor what i actually have to do with that. By browsing specs, i've thought that i need to set `config.i18n.default_locale` but it didn't helped.

Thanks in advance for any clues.

**Comment by pronix** [comment]
which version of spree are you using ?

**Comment by mbajur** [comment]
branch 3-0-stable

**Comment by pronix** [comment]
it is not supported. so you are welcome pull requests ;)

**Comment by mbajur** [comment]
Oh, i've missed that it's for 1.x. So - it seems that i need to spend some
time on trying to integrate that with 3.0 :) I'm a spree newbie so i'm not
sure if i'm gonna figure anything out but i will let you know about the
results for sure.
